org: "nathan85"
service: "serverless-boilerplate"
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    CONFIG_REGION: ${self:provider.region}

functions:
  buildCircle:
    name: buildCircle-${self:provider.stage}
    handler: ./src/handlers/func1/index.handler
    events:
      - http:
          path: /func1
          method: GET
          cors: true
